#!/bin/bash
# Setup script for GitHub Pages deployment

echo "OpenClaw Research Site - GitHub Setup"
echo "======================================"
echo ""
echo "Since GitHub CLI is not configured, follow these manual steps:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: openclaw-research"
echo "   - Make it public"
echo "   - Don't initialize with README"
echo ""
echo "2. Push this repository:"
echo "   cd /root/.openclaw/workspace/research-site"
echo "   git remote add origin https://github.com/YOUR_USERNAME/openclaw-research.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Enable GitHub Pages:"
echo "   - Go to repository Settings > Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main / (root)"
echo "   - Save"
echo ""
echo "4. Your site will be available at:"
echo "   https://YOUR_USERNAME.github.io/openclaw-research"
echo ""
echo "Current repository location:"
echo "   /root/.openclaw/workspace/research-site"
